In [1]:
import pandas as pd

In [12]:
messages = pd.read_csv('spam_ham_dataset (1).csv')

In [ ]:
import re
import nltk
nltk.download('stopwords')

In [13]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500)
X = cv.fit_transform(corpus).toarray()

In [22]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
y=pd.get_dummies(messages['label'])
y=y.iloc[:,1].values

In [16]:
print(y)

[0 0 0 ... 0 0 1]


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [18]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [19]:
y_pred=spam_detect_model.predict(X_test)

In [26]:
print(y_pred.reshape(len(y_pred),1))

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [1]]
